name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race -covermode=atomic -coverprofile=coverprofile.out ./...

      - name: Install Goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send Coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=coverprofile.out -service=github
